task:
  description: use RL methods to optimize traffic signal control problems
  task_name: tsc

simulator:
# necessary and distinctive parameters for simulators
  interval: 1.0
  seed: 0
  dir: data/raw_data

  saveReplay: False
  report_log_mode: normal # cbengine
  log_dir: data/output_data

  no_warning: True
  gui: False

  rlTrafficLight: True

traffic:
  yellow_length: 5
  action_interval: 10
  start_time_epoch: 0
  max_time_epoch: 3600







