includes:
  - configs/tsc/base.yml

model:
  name: frap
  train_model: True
  n_layers: 2
  rotation: true
  conflict_matrix: true
  merge: multiply
  d_dense: 20
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  demand_shape: 1

  one_hot: False
  phase: True

trainer: 
  learning_start: 1000

world:

  phases: ['NT_ST','WT_ET','NL_SL','WL_EL','NL_NT','SL_ST','WL_WT','EL_ET']
  
  list_lane_order: ['ET','EL','ST','SL','WT','WL','NT','NL']

  phase_expansion: {
    1: [0, 0, 1, 0, 0, 0, 1, 0],
    2: [1, 0, 0, 0, 1, 0, 0, 0],
    3: [0, 0, 0, 1, 0, 0, 0, 1],
    4: [0, 1, 0, 0, 0, 1, 0, 0],
    5: [0, 0, 0, 0, 0, 0, 1, 1],
    6: [0, 0, 1, 1, 0, 0, 0, 0],
    7: [0, 0, 0, 0, 1, 1, 0, 0],
    8: [1, 1, 0, 0, 0, 0, 0, 0]
  }

  phase_expansion_4_lane: {1: [0,0,1,1],2: [1,1,0,0]}

  signal_config: {
    grid4x4: {
      # phases: ['NT_ST','NL_SL','NL_NT','SL_ST','ET_WT','EL_WL','WT_WL','EL_ET']
      phase_pairs: [[1, 7], [2, 8], [1, 2], [7, 8], [4, 10], [5, 11], [10, 11], [4, 5]],
      valid_acts: null,
      cf_order: {'N': 0,'E': 1,'S': 2, 'W': 3},
      sumo_order: {'N': 2,'E': 3,'S': 0, 'W': 1}
    },
    hz1x1: {
      # phases: ['ET_WT','NT_ST','EL_WL','NL_SL','WL_WT','EL_ET','SL_ST','NL_NT']
      phase_pairs: [[2, 6], [0, 4], [3, 7], [1, 5], [6, 7], [2, 3], [4, 5], [0, 1]],
      valid_acts: null,
      cf_order: {'N': 0,'E': 1,'S': 2, 'W': 3},
      sumo_order: {'N': 2,'E': 3,'S': 0, 'W': 1}
    },
    hz4x4: {
      # phases: ['ET_WT','NT_ST','EL_WL','NL_SL','WL_WT','EL_ET','SL_ST','NL_NT']
      phase_pairs: [[4, 10], [1, 7], [3, 9], [0, 6], [9, 10], [3, 4], [6, 7], [0, 1]],
      valid_acts: null,
      cf_order: {'N': 0,'E': 1,'S': 2, 'W': 3},
      sumo_order: {'N': 2,'E': 3,'S': 0, 'W': 1}
    },
    cologne1: {
      # phases: ['NT_ST','NL_SL','ET_WT','EL_WL']
      phase_pairs: [[1, 5], [0, 4], [3, 7], [2, 6]],
      valid_acts: null,
      cf_order: {'N': 3,'E': 0,'S': 1, 'W': 2},
      sumo_order: {'N': 1,'E': 2,'S': 3, 'W': 0}
    },
    cologne3: {
      # phases: ['NT_ST','NL_SL','WT_ET','WL_EL']
      # phase_pairs: [[1, 7], [2, 8], [1, 2], [7, 8]],
      phase_pairs: [[1, 7], [2, 8], [1, 2], [7, 8], [4, 10], [5, 11], [10, 11], [4, 5]],
      valid_acts: {
        'GS_cluster_2415878664_254486231_359566_359576': {4: 0, 5: 1, 0: 2, 1: 3},
        '360086': {4: 0, 5: 1, 0: 2, 1: 3},
        '360082': {4: 0, 5: 1, 1: 2}
      },
      lane_order: {
        '360082': {0: 0, 1: 1, 4: 2, 6: 3, 7: 4},
        '360086': {0: 0, 1: 1, 4: 2, 6: 3, 7: 4, 10: 5},
        'cluster_2415878664_254486231_359566_359576': {0: 0, 1: 1, 3: 2, 4: 3, 6: 4, 7: 5, 9: 6, 10: 7}
      },
      cf_order: {
        '360082': {'N': 0,'E': 1,'S': 2, 'W': -1},
        '360086': {'N': 0,'E': 1,'S': 2, 'W': 3},
        'cluster_2415878664_254486231_359566_359576': {'N': 0,'E': 1,'S': 2, 'W': 3}
        },
      sumo_order: {
        '360082': {'N': 1,'E': 2,'S': 0, 'W': -1},
        '360086': {'N': 2,'E': 3,'S': 0, 'W': 1},
        'cluster_2415878664_254486231_359566_359576': {'N': 2,'E': 3,'S': 0, 'W': 1}
      }
    }
  }