includes:
  - configs/tsc/base.yml


model:
  name: maddpg_v2
  local_q_learn: False
  graphic: False
  vehicle_max: 1
  alpha: 0.01
  beta: 0.01
  tau: 0.01
  fc1: 64
  fc2: 64
  batch_size: 1024
  gamma: 0.99
  epsilon: 0.5
  epsilon_decay: 0.99
  epsilon_min: 0.01
  grad_clip: 0.5
  NEIGHBOR_NUM: 4
  NEIGHBOR_EDGE_NUM: 4


trainer:
  thread: 4
  ngpu: -1
  learning_start: 2000
  buffer_size: 10000
  steps: 3600
  test_steps: 3600
  action_interval: 20
  episodes: 2000
  update_model_rate: 30
  update_target_rate: 30
  # save_dir: data/output_data/task_name/dataset_dir/model_name
  # load_dir: data/output_data/task_name/dataset_dir/model_name
  # log_dir: log/task_name/dataset_dir/model_name/


logger:
  log_dir: "logger"
  replay_dir: "replay"
  save_dir: "model"
  data_dir: "dataset"
  get_attention: False
  ave_model: True
  save_model: True
  save_rate: 3000
  train_model: True
  test_model: True
  load_model: False


traffic:
  one_hot: False
  phase: False
  thread_num: 4
  ACTION_PATTERN: "set"
  MIN_ACTION_TIME: 10
  YELLOW_TIME: 5
  ALL_RED_TIME: 0
  NUM_PHASES: 8
  NUM_LANES: 1
  ACTION_DIM: 2
  MEASURE_TIME: 10
  IF_GUI: True
  DEBUG: False
  INTERVAL: 1
  SAVEREPLAY: True
  RLTRAFFICLIGHT: True