from . import BaseAgent
from common.registry import Registry
from generator import LaneVehicleGenerator, IntersectionPhaseGenerator, IntersectionVehicleGenerator
import numpy as np
import gym


@Registry.register_model('maxpressure')
class MaxPressureAgent(BaseAgent):
    '''
    MaxPressureAgent using Max-Pressure method to control traffic light.
    '''
    def __init__(self, world, rank):
        super().__init__(world)
        self.rank = rank
        inter_id = self.world.intersection_ids[self.rank]
        self.inter_obj = self.world.id2intersection[inter_id]

        self.action_space = gym.spaces.Discrete(len(self.inter_obj.phases))
        self._create_generators()
        self.model = None
        
        # the minimum duration of time of one phase
        self.t_min = Registry.mapping['model_mapping']['setting'].param['t_min']


    def _create_generators(self):
        self.ob_generator = LaneVehicleGenerator(self.world, self.inter_obj,
                                                 ["lane_count"], in_only=True, average=None)
        self.phase_generator = IntersectionPhaseGenerator(self.world, self.inter_obj,
                                                          ['phase'], targets=['cur_phase'], negative=False)
        self.reward_generator = LaneVehicleGenerator(self.world, self.inter_obj,
                                                     ["lane_waiting_count"], in_only=True, average="all",
                                                     negative=True)
        self.queue = LaneVehicleGenerator(self.world, self.inter_obj,
                                                     ["lane_waiting_count"], in_only=True, average="all",
                                                     negative=False)
        self.delay = LaneVehicleGenerator(self.world, self.inter_obj,
                                                     ["lane_delay"], in_only=True, average="all",
                                                     negative=False)


    def reset(self):
        '''
        reset
        Reset information, including ob_generator, phase_generator, queue, delay, etc.

        :param: None
        :return: None
        '''
        self._create_generators()

    def __repr__(self):
        return 'Maxpressure Agent has no Network model'

    def get_ob(self):
        '''
        get_ob
        Get observation from environment.

        :param: None
        :return x_obs: observation generated by ob_generator
        '''
        x_obs = []
        x_obs.append(self.ob_generator.generate())
        x_obs = np.array(x_obs, dtype=np.float32)
        return x_obs

    def get_reward(self):
        '''
        get_reward
        Get reward from environment.

        :param: None
        :return: reward generated by reward_generator
        '''
        rewards = []
        rewards.append(self.reward_generator.generate())
        rewards = np.squeeze(np.array(rewards))
        assert rewards.size == 1
        return rewards
    
    def get_phase(self):
        '''
        get_phase
        Get current phase of intersection(s) from environment.

        :param: None
        :return: current phase generated by phase_generator
        '''
        phase = [self.phase_generator.generate()]
        phase = np.array(phase, dtype=np.int8)
        return phase
    

    def get_action(self, ob, phase, test=True):
        '''
        get_action
        Generate action.

        :param ob: observation, the shape is (1,12)
        :param phase: current phase, the shape is (1,)
        :param test: boolean, decide whether is test process
        :return action: action that has the highest score
        '''
        # get lane pressure
        lvc = self.world.get_info("lane_count")
        if self.inter_obj.current_phase_time < self.t_min:
            return self.inter_obj.current_phase

        max_pressure = None
        action = -1
        for phase_id in range(len(self.inter_obj.phases)):
            pressure = sum([lvc[start] - lvc[end] for start, end in self.inter_obj.phase_available_lanelinks[phase_id]])
            if max_pressure is None or pressure > max_pressure:
                action = phase_id
                max_pressure = pressure
        return action

    def get_queue(self):
        '''
        get_queue
        Get queue length of intersection.

        :param: None
        :return: total queue length
        '''
        queue = []
        queue.append(self.queue.generate())
        queue = np.sum(np.squeeze(np.array(queue)))
        return queue

    def get_delay(self):
        '''
        get_delay
        Get delay of intersection.

        :param: None
        :return: total delay
        '''
        delay = []
        delay.append(self.delay.generate())
        delay = np.sum(np.squeeze(np.array(delay)))
        return delay

